# Generated by Django 4.0.6 on 2022-08-01 20:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('type_Of_User', models.CharField(blank=True, choices=[('S', 'Seller'), ('B', 'Buyer'), ('D', 'Delivery Person')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'USER',
                'verbose_name_plural': 'USERS',
                'db_table': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='BUYER ID')),
                ('buyer_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=12)),
                ('longitude', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=10)),
                ('created_Date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USER ID')),
            ],
            options={
                'verbose_name': 'BUYER',
                'verbose_name_plural': 'BUYERS',
                'db_table': 'buyers',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='CART ID')),
                ('unit_Price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'CART',
                'verbose_name_plural': 'CARTS',
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Delivery_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='DERIVERY ID')),
                ('shop_id', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=200)),
                ('status', models.TextField()),
            ],
            options={
                'verbose_name': 'DELIVERY DETAIL',
                'verbose_name_plural': 'DELIVERY DETAILS',
                'db_table': 'delivery_details',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='PRODUCT ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('posted_Date', models.DateTimeField()),
                ('description', models.TextField()),
                ('manufactured_Date', models.DateField()),
                ('brand_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'PRODUCT',
                'verbose_name_plural': 'PRODUCTS',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='SELLER ID')),
                ('Contact', models.CharField(max_length=12)),
                ('longitude', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USER ID')),
            ],
            options={
                'verbose_name': 'SELLER',
                'verbose_name_plural': 'SELLERS',
                'db_table': 'sellers',
            },
        ),
        migrations.CreateModel(
            name='Shop_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='CATEGORY ID')),
                ('category_name', models.CharField(max_length=200)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.seller', verbose_name='SELLER ID')),
            ],
            options={
                'verbose_name': 'SHOP CATEGORY',
                'verbose_name_plural': 'SHOP CATEGORIES',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Sub_shop_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='SUB CATEGORY ID')),
                ('sub_category_name', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='ShopSubCategoryPicture')),
                ('shop_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.shop_categories', verbose_name='SHOP CATEGORY ID')),
            ],
            options={
                'verbose_name': 'SUB SHOP CATEGORY',
                'verbose_name_plural': 'SUB SHOP CATEGORIES',
                'db_table': 'sub_categories',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='SHOP ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=10)),
                ('Contact', models.CharField(max_length=12)),
                ('registered_Date', models.DateField()),
                ('logo', models.ImageField(blank=True, upload_to='seller logo')),
                ('shop_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.shop_categories', verbose_name='SHOP CATEGORY ID')),
            ],
            options={
                'verbose_name': 'SHOP',
                'verbose_name_plural': 'SHOPS',
                'db_table': 'shops',
            },
        ),
        migrations.CreateModel(
            name='Product_Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='PICTURE ID')),
                ('picture_name', models.CharField(max_length=200)),
                ('product_picture', models.ImageField(blank=True, upload_to='ProductPicture')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='PRODUCT ID')),
            ],
            options={
                'verbose_name': 'PRODUCT PICTURE',
                'verbose_name_plural': 'PRODUCT PICTURES',
                'db_table': 'product_pictures',
            },
        ),
        migrations.CreateModel(
            name='Product_Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ATTRIBUTE ID')),
                ('attribute_name', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='PRODUCT ID')),
            ],
            options={
                'verbose_name': 'PRODUCT ATTRIBUTE',
                'verbose_name_plural': 'PRODUCT ATTRIBUTES',
                'db_table': 'product_attributes',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop_category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.shop_categories', verbose_name='SHOP CATEGORY ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sub_shop_categories', verbose_name='SUB CATEGORY ID'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ORDER ID')),
                ('cutomer_id', models.CharField(max_length=200)),
                ('created_Date', models.DateTimeField(auto_now_add=True)),
                ('buyer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.buyer', verbose_name='BUYER ORDER ID')),
                ('cart', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart', verbose_name='CART ID')),
            ],
            options={
                'verbose_name': 'ORDER',
                'verbose_name_plural': 'ORDERS',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Delivery_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='DELIVERY PERSON ID')),
                ('Contact', models.CharField(max_length=12)),
                ('longitude', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('created_Date', models.DateTimeField(auto_now_add=True)),
                ('person', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.delivery_details', verbose_name='DELIVERY DETAIL ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USER ID')),
            ],
            options={
                'verbose_name': 'DELIVERY PERSON',
                'verbose_name_plural': 'DELIVERY PERSONS',
                'db_table': 'delivery_persons',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='PRODUCT ID'),
        ),
    ]
