# Generated by Django 4.0.6 on 2022-08-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_categories',
            name='seller_id',
        ),
    ]
