# Generated by Django 4.0.6 on 2022-08-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_shops_contact_alter_shops_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='Contact',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='latitude',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='longitude',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
