# Generated by Django 4.0.6 on 2022-08-05 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_user_full_name_alter_seller_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='seller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.seller', verbose_name='SHOP OWNER'),
        ),
    ]
