# Generated by Django 4.0.6 on 2022-08-05 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_shops_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='SHOP User'),
        ),
    ]
