# Generated by Django 4.0.6 on 2022-08-06 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_shops_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_shop_Categories',
            new_name='Sub_Categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category_id',
        ),
        migrations.AlterField(
            model_name='shops',
            name='Contact',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='address',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='latitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='registered_Date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.shop_categories', verbose_name='SHOP CATEGORY ID'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
