# Generated by Django 4.0.6 on 2022-08-06 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_sub_shop_categories_sub_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.sub_categories', verbose_name='SUB CATEGORY ID'),
        ),
    ]
