# Generated by Django 4.0.6 on 2022-08-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_shops_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='user_id',
        ),
    ]
