# Generated by Django 4.0.6 on 2022-08-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_shops_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop_category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='shop_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.shops', verbose_name='Shop ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Product ID'),
        ),
    ]
