# Generated by Django 4.0.6 on 2022-08-07 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cutomer_id',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.buyer', verbose_name='Buyer ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart_id',
            field=models.OneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart', verbose_name='Cart ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_Date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Order ID'),
        ),
    ]
