# Generated by Django 4.0.6 on 2022-08-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_order_buyer_order_remove_order_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='buyer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.buyer', verbose_name='Buyer ID'),
        ),
    ]
