# Generated by Django 4.0.6 on 2022-08-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_product_attribute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='posted_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Product_Picture',
        ),
    ]
