# Generated by Django 4.0.6 on 2022-08-10 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_product_posted_date_delete_product_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='PICTURE ID')),
                ('picture_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_picture', models.ImageField(blank=True, upload_to='ProductPicture')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='mainapp.product', verbose_name='PRODUCT ID')),
            ],
            options={
                'verbose_name': 'PRODUCT PICTURE',
                'verbose_name_plural': 'PRODUCT PICTURES',
                'db_table': 'product_pictures',
            },
        ),
    ]
