# Generated by Django 4.0.6 on 2022-08-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_Price',
            field=models.IntegerField(default=0),
        ),
    ]
