# Generated by Django 4.0.6 on 2022-08-12 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_remove_cart_products_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_Date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_Price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.buyer', verbose_name='Buyer ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Cart ID'),
        ),
    ]
