# Generated by Django 4.0.6 on 2022-08-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_rename_created_date_order_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profiles/profile-photo.jpg', upload_to='profiles', verbose_name='Profile Picture'),
        ),
    ]
