# Generated by Django 4.0.6 on 2022-08-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
