# Generated by Django 4.0.6 on 2022-08-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_remove_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profiles/profile-photo.jpg', upload_to='profiles', verbose_name='Profile Picture'),
        ),
    ]
