# Generated by Django 4.0.6 on 2022-08-15 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_alter_user_profile_pic'),
        ('mainapp', '0025_user_profile_pic'),
    ]

    operations = [
    ]
