# Generated by Django 4.0.6 on 2022-08-15 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_merge_20220815_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='unit_Price',
        ),
    ]
