# Generated by Django 4.0.6 on 2022-08-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_remove_cart_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='contact',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='created_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='latitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
