# Generated by Django 4.0.6 on 2022-08-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_alter_buyer_address_alter_buyer_buyer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_categories',
            name='picture',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='Category Pics', verbose_name='Picture'),
        ),
        migrations.RemoveField(
            model_name='sub_categories',
            name='shop_category_id',
        ),
        migrations.AddField(
            model_name='sub_categories',
            name='shop_category_id',
            field=models.ManyToManyField(to='mainapp.shop_categories', verbose_name='Sub Categories'),
        ),
    ]
