# Generated by Django 4.0.6 on 2022-08-16 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_shop_categories_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_categories',
            name='shop_category_id',
        ),
        migrations.AddField(
            model_name='sub_categories',
            name='shop_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.shop_categories', verbose_name='Sub Categories'),
        ),
    ]
