# Generated by Django 4.0.6 on 2022-08-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_remove_sub_categories_shop_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default='True', verbose_name='Active'),
        ),
    ]
