# Generated by Django 4.0.6 on 2022-08-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_order_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default='Yes', verbose_name='Active'),
        ),
    ]
