# Generated by Django 4.0.6 on 2022-08-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_alter_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
